config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :sign_in
      post :sign_in
      get :me
      get :sign_up
      post :sign_up

      get :me_detail
    end
  end

  # 楼层
  resources :floors, only: [:index, :create, :edit, :new, :show]

  # 班级
  resources :clazzs, only: [:index, :new, :create, :show]

  namespace :api do
    # 统计API
    resources :statistics, only: [:index] do
      collection do
        post :floor
      end
    end

    # 房间
    resources :rooms, only: [:update] do
      member do
        post :create_station
      end
    end

    # 楼层API
    resources :floors, only: [:index, :show] do
      member do
        post :create_room

        # 获取楼层房间
        get :rooms
      end

      collection do
        # 所有楼层->所有房间->房间内的基站 隐射表
        get :station_mapping
      end
    end

    # 基站数据更新
    resources :stations, only: [:update]

    # 班级
    resources :clazzs, only: [:index, :update, :create]

    # 语音消息
    resources :audio_messages do
      member do
        # 设置已读
        post :set_read
      end
    end

    # 老师
    resources :teachers do
      collection do
        # 获取评论
        get :comments

        get :audio_messages

        # 获取魔法棒配置
        get :sticker_configs

        # 更新魔法棒配置
        post :update_sticker_config

        # 添加魔法棒配置
        post :create_sticker_config
      end
    end

    # 轨迹
    resources :tracks, only: [:create]
  end

  namespace :board do
    # 养老院
    resources :nursing_home, only: [:index] do
      collection do
        # 获取页面数据
        get :page_data

        # 获取在线人员即时位置信息
        get :realtime_geo_data

        # 获取一天的历史轨迹
        get :footprints
      end
    end

    # 班级
    resources :clazzs, only: [:index, :show] do
      member do
        get :students_list
        get :comments
      end

      collection do
        # 创建评论
        post :create_comment

        # 创建语音信息
        post :create_audio_message

        # 获取教师列表接口
        get :teachers
      end
    end


  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)      not null              # 用户名
#  password   :string(255)      not null              # 密码
#  permission :integer          default("0")          # 权限bit
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  avatar     :string(255)                            # 头像
#

class User < ActiveRecord::Base
  # 通用查询方法
  include Concerns::Query::Methods

  # 挂载头像
  mount_uploader :avatar, CadUploader

  # 关联老师
  has_one :teacher

  # 默认统计时效
  module StatisticThreshold
    MIN = 500.minutes
    DAY = 3.hours
  end

  # 用户的历史轨迹
  # 只返回每次数据中信号最强的数据
  def footprints (from_time=(Time.now - 5.minutes), limit=10)
    Payload.find_by_sql("SELECT p1.*,floor.*  FROM `payloads` p1 LEFT JOIN `payloads` p2 ON (p1.`student_id` = p2.`student_id` AND p1.`token` = p2.`token` AND p1.`strength` < p2.`strength` ) LEFT JOIN `stations` AS station ON ( station.`id` = p1.`station_id` ) LEFT JOIN `rooms` as room ON (room.`id` = station.`room_id` ) LEFT JOIN `floors` AS floor ON (floor.`id` = room.`floor_id` ) WHERE p1.created_at >= '#{from_time}' AND p2.`id` IS NULL AND floor.id IS NOT NULL AND p1.`student_id` = #{self.id}   ORDER BY p1.`created_at` DESC  LIMIT #{limit}")
  end

  # 网页显示名称
  def show_name
    if self.teacher.present?
      return self.teacher.name
    else
      return ''
    end
  end

  #
  # 每层楼的在线用户数统计,按[{count:10, floor:{FLOOR OBJECT}]返回
  #
  # @param options [Hash]
  # option options [minute_threshold] :多少分钟内统计有效(默认:5, 表示5分钟以前的数据不计入统计)
  #
  # @return [Response, Array] 状态，[{count:10, floor:{FLOOR OBJECT}]
  #
  def self.statistics_for_online_count_of_floors (options = {})
    data = []
    response = Response.__rescue__ do |res|
      from_time= options[:minute_threshold] || (Time.now - StatisticThreshold::MIN)
      # result = ActiveRecord::Base.connection.execute("SELECT COUNT(IF(p1.`created_at` >  '#{from_time}', 1, null)) AS count, floor.id, floor.name  FROM `payloads` p1
      #                                                 LEFT JOIN `payloads` p2 ON (p1.`student_id` = p2.`student_id` AND p1.`id` < p2.`id` )
      #                                                 LEFT JOIN `stations` AS station ON ( station.`id` = p1.`station_id` )
      #                                                 LEFT JOIN `rooms` as room ON (room.`id` = station.`room_id` )
      #                                                 RIGHT JOIN `floors` AS floor ON (floor.`id` = room.`floor_id` )
      #                                                 WHERE  p2.`id` IS NULL
      #                                                 GROUP BY floor.`id`")

      result = ActiveRecord::Base.connection.execute("SELECT SUM(case when T3.floor_id IS NULL then 0 else 1 end) AS count, f.`id`,f.`name`
                                                      FROM `floors` AS f
                                                      LEFT JOIN(
                                                    Select R.`floor_id`
                                                      from(
                                                    select *
                                                      from(
                                                    SELECT p1.*
                                                      FROM `payloads` p1
                                                     WHERE p1.`created_at`> '#{from_time}'
                                                     ORDER BY p1.`id` DESC) As T
                                                     GROUP BY T.`student_id`) as T2 JOIN `stations` S on T2.station_id= S.`id` JOIN `rooms` as R ON R.`id`= S.`room_id`) AS T3 ON T3.floor_id= F.`id`
                                                     GROUP BY f.`name` ")

      # row structure
      # [count, floor_id, floor_name]
      result.each do|row|
        data << {count: row[0], floor: {id: row[1], name: row[2]}}
      end
    end
    return response, data
  end

  #
  # 某层楼的在线用户数统计,按[{count:10, room:{Room Object}]返回
  #
  # @param options [Hash]
  # option options [minute_threshold] :多少分钟内统计有效(默认:5, 表示5分钟以前的数据不计入统计)
  # option options [floor_id] :楼层id
  #
  # @return [Response, Array] 状态，[{count:10, room:{Room Object}]
  #
  def self.statistics_for_online_count_of_rooms (options = {})
    data = []
    response = Response.__rescue__ do |res|
      from_time= options[:minute_threshold] || (Time.now - StatisticThreshold::MIN)
      floor_id= options[:floor_id]

      res.__raise__(Response::Code::ERROR, '参数错误') if floor_id.blank?

      floor = Floor.query_first_by_id floor_id

      res.__raise__(Response::Code::ERROR, '楼层不存在') if floor.blank?

      # result = ActiveRecord::Base.connection.execute("SELECT COUNT(IF(p1.`created_at` >  '#{from_time}', 1, null)) AS count, room.id, room.name FROM `payloads` p1
      #                                                 LEFT JOIN `payloads` p2 ON (p1.`student_id` = p2.`student_id` AND p1.`id` < p2.`id` )
      #                                                 LEFT JOIN `stations` AS station ON ( station.`id` = p1.`station_id` )
      #                                                 RIGHT JOIN `rooms` as room ON (room.`id` = station.`room_id`)
      #                                                 WHERE  p2.`id` IS NULL AND room.`floor_id` = #{floor.id}
      #                                                 GROUP BY room.id
      #                                                 ")

      result = ActiveRecord::Base.connection.execute("SELECT COUNT(RESULT.name) as count, RESULT.id, RESULT.name FROM  (SELECT room.* FROM (SELECT * FROM (
                                                                SELECT p1.*
                                                                FROM `payloads` p1
                                                                WHERE p1.`created_at`>= '#{from_time}'
                                                                ORDER BY p1.`id` DESC) AS T
                                                            GROUP BY T.`student_id` )AS R  LEFT JOIN `stations` AS station ON ( station.`id` = R.`station_id` )
                                                            LEFT JOIN `rooms` as room ON (room.`id` = station.`room_id`)
                                                            WHERE room.`floor_id` = #{floor.id}) AS RESULT GROUP BY RESULT.name")
      # row structure
      # [count, room_id, room_name]
      data = result.map do|row|
        {count: row[0], room: {id: row[1], name: row[2]}}
      end

      Room.query_by_options({floor_id: floor.id}).where.not(id: result.map {|row| row[1]}).each do |room|
        data << {count: 0, room: {id: room.id, name: room.name}}
      end
    end
    return response, data
  end

  #
  # 用户登录接口
  #
  # @param options [Hash]
  # option options [user] :用户hash
  # option user [username] :用户名
  # option user [password] :密码
  #
  # @return [Response, Array] 状态，基站列表
  #
  def self.sign_in_for_api(options = {})
    user = nil
    response = Response.__rescue__ do |res|
      user = options[:user]

      res.__raise__(Response::Code::ERROR, '参数错误') if user.blank?

      username, password = user[:username], user[:password]

      res.__raise__(Response::Code::ERROR, '用户名和密码不能为空') if username.blank? || password.blank?


      user = self.query_first_by_options({username: username, password: password})

      res.__raise__(Response::Code::ERROR, '用户名或者密码错误') if user.blank?
    end

    return response, user
  end

  #
  # 用户注册接口
  #
  # @param options [Hash]
  # option options [username] :用户名
  # option options [password] :密码
  # option options [real_name] :真名
  # option options [device_id] :设备号
  # option options [subject] :学科
  #
  # @return [Response, Array] 状态，基站列表
  #
  def self.sign_up_with_options(options={})
    user = nil
    response = Response.__rescue__ do |res|
      transaction do
        username, password, real_name, device_id, subject = options[:username], options[:password], options[:real_name], options[:device_id], options[:subject]

        res.__raise__(Response::Code::ERROR, '用户名不能为空') if username.blank?
        res.__raise__(Response::Code::ERROR, '密码不能低于8位') if password.blank? || password.length < 8
        res.__raise__(Response::Code::ERROR, '真名不能为空') if real_name.blank?
        res.__raise__(Response::Code::ERROR, '设备号不能为空') if device_id.blank?
        res.__raise__(Response::Code::ERROR, '学科不能为空') if subject.blank?

        # 检测教师重复注册
        teacher_exist = Teacher.query_first_by_options(device_id: device_id)

        res.__raise__(Response::Code::ERROR, '此设备号已经注册过老师,不能再注册') if teacher_exist.present?

        user = User.new
        user.username = username
        user.password = password
        user.save!

        teacher = Teacher.new
        teacher.name = real_name
        teacher.device_id = device_id
        teacher.subject = subject
        teacher.user = user
        teacher.save!
      end
    end

    return response, user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :user_authenticate, only:[:sign_in, :sign_up]

  def sign_in
    if request.method_symbol == :post
      @response, @user = User.sign_in_for_api(params)

      if @response.is_successful?

        session[:user_id] = @user.id

        redirect_to me_users_path
      end
    end
  end

  def me
  end

  # 注册
  def sign_up
    if request.method_symbol == :post
      @response, @user = User.sign_up_with_options(params)

      if @response.is_successful?

        session[:user_id] = @user.id

        redirect_to me_users_path
      end
    end
  end

  def me_detail
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/me.html.slim
body.hold-transition.skin-black.sidebar-mini ng-controller='PortalController'
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    /! /.sidebar-menu
    /! /.sidebar
    /! Content Wrapper. Contains page content
    .content-wrapper
      /! Content Header (Page header)
      section.content-header
        h1
        |基本数据统计

      /! Main content
      section.content
        .row
          .col-md-8.col-md-offset-2
            .box.box-danger
              .box-header.with-border
                h3.box-title 楼层在线统计
                .box-tools.pull-right
                  button.btn.btn-box-tool data-widget="collapse" type="button"
                    i.fa.fa-minus
              .box-body
                canvas#pieChartForOnlineCountOfFloor height="370" style="height: 400px" width="741"
              .overlay ng-show="isLoadingForOnLineCountOfFloor"
                i.fa.fa-refresh.fa-spin

    /! /.box-body

    == include_slim 'app/views/common/footer'
    == include_slim 'app/views/common/control'

app/views/users/me_detail.slim
body.hold-transition.skin-black.sidebar-mini ng-controller='MeDetailController'
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    /! /.sidebar-menu
    /! /.sidebar
    /! Content Wrapper. Contains page content
    .content-wrapper
      /! Main content
      section.content
        .row
          .col-md-8
            /! Widget: user widget style 1
            .box.box-widget.widget-user
              /! Add the bg color to the header using any of the bg-* classes
              .widget-user-header.bg-aqua-active
                h3.widget-user-username = params[:user].show_name
                h5.widget-user-desc = params[:user].teacher.subject
              .widget-user-image
                img.img-circle alt=("User Avatar") src="http://7xnsaf.com1.z0.glb.clouddn.com/geo/avatar/male.png" /
              .row
                .col-md-12 style="padding: 50px;padding-bottom: 10px;"
                  table.table.table-bordered
                    tbody
                      tr
                        th 按键编号
                        th 评论原因
                        th style=("width: 100px") 操作
                      tr ng-repeat="sticker_config in sticker_configs"
                        td
                          span ng-bind="sticker_config.sticker_key"

                        td
                          input.form-control placeholder=("上课表现优秀") type="text" ng-disabled='!sticker_config.isEditing' ng-model='sticker_config.value'
                        td
                          a.btn.btn-social-icon.btn-danger ng-show='!sticker_config.isEditing' ng-click='sticker_config.isEditing = true;'
                            i.fa.fa-pencil-square-o
                          a.btn.btn-social-icon.btn-twitter ng-show='sticker_config.isEditing' ng-click='UpdateStickerConfig(sticker_config)'
                            i.fa.fa-floppy-o
                          a.btn.btn-social-icon.btn-danger.pull-right style="line-height:34px; text-align: center;" ng-show='sticker_config.isEditing' ng-click='sticker_config.isEditing = false;' 取消
                      tr
                        td
                          input.form-control placeholder=("0,1,2,3...") type="text" ng-model='tempStickerConfig.sticker_key'
                        td
                          input.form-control placeholder=("上课表现优秀") type="text" ng-model='tempStickerConfig.value'
                        td
                          a.btn.btn-social-icon.btn-danger ng-click='CreateStickerConfig(tempStickerConfig)'
                            i.fa.fa-floppy-o

              .box-footer
                .row
                  .col-sm-6.border-right
                    .description-block
                      h5.description-header ng-bind='comments.length'
                      span.description-text 今日点赞
                  /! /.description-block
                  /! /.col
                  .col-sm-6.border-right
                    .description-block
                      h5.description-header ng-bind='allCommentsCount'
                      span.description-text 总点赞


              .overlay ng-show="isGettingStickerConfig || isCreatingStickerConfig"
                i.fa.fa-refresh.fa-spin
          .col-md-4
            #room-rightbar.nav-tabs-custom
              ul.nav.nav-tabs
                li.active
                  a aria-expanded="true" data-toggle="tab" href="#comments"  今日点赞
                li
                  a aria-expanded="false" data-toggle="tab" href="#audio-messages"  语音消息

              .tab-content
                #comments.tab-pane.active
                  .info-box ng-repeat='comment in comments'
                    span.info-box-icon.bg-red
                      i.fa.fa-star-o
                    .info-box-content
                      span.info-box-number
                        span.text-info ng-bind='comment.student.name'
                        span ng-bind="'同学因为' + comment.content + '得到了一个赞'"
                      br
                      br
                      span ng-bind="comment.teacher.subject+'老师: ' + comment.teacher.name"
                      span.info-box-text.pull-right ng-bind='comment.show_time'
                  div ng-show='comments == null || comments.length < 1' style='text-align:center;'
                    |今天还未点过赞哦
                #audio-messages.tab-pane
                  .info-box ng-repeat='audio_message in audio_messages'
                    span.info-box-icon.bg-red ng-click='PlayAudio(audio_message)' style='cursor:pointer'
                      i.fa.fa-file-audio-o
                    .info-box-content
                      button.pull-right ng-click='SetReaded(audio_message)' 设为已读
                      span.info-box-number
                        span.text-info ng-bind='audio_message.student.name'
                        span 发来了一条语音消息, 点击喇叭收听
                  div ng-show='audio_messages == null || audio_messages.length < 1' style='text-align:center;'
                    |暂无未读消息哦

    == include_slim 'app/views/common/footer'
    == include_slim 'app/views/common/control'

app/views/users/sign_in.html.slim
javascript:
  $(document).on('turbolinks:load', function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });

body.hold-transition.login-page
.login-box
  .login-logo
    b> 校园蓝牙基站系统
    br
    h4 栖格科技
  /! /.login-logo
  .login-box-body
    - if @response && !@response.is_successful?
      p.login-box-msg
        .alert.alert-warning.alert-dismissible
          button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
          i.icon.fa.fa-warning 用户名或密码错误
    = form_tag sign_in_users_path, name: 'sign_in_form', method: :post, novalidate: 'novalidate', remote: true
      .form-group.has-feedback
        input.form-control placeholder="Username" type="username" name="user[username]" /
        span.glyphicon.glyphicon-user.form-control-feedback
      .form-group.has-feedback
        input.form-control placeholder="Password" type="password" name="user[password]" /
        span.glyphicon.glyphicon-lock.form-control-feedback
      .row
        .col-xs-8
          .checkbox.icheck
            label
              input type="checkbox" /
              | 记住登录
        /! /.col
        .col-xs-4
          button.btn.btn-primary.btn-block.btn-flat type="submit"  登录
    /! /.col
    .social-auth-links.text-center
      p - 或者 -
      a.btn.btn-block.btn-social.btn-facebook.btn-flat href=(sign_up_users_path)
        i.fa.fa-user-plus
        | 新用户注册
      a.btn.btn-block.btn-social.btn-google.btn-flat href="#"
        i.fa.fa-question-circle
        | 忘记密码

app/views/users/sign_up.slim
javascript:
  //$(document).on('turbolinks:load', function () {
  //  $('input').iCheck({
  //    checkboxClass: 'icheckbox_flat-blue',
  //    radioClass: 'iradio_square-blue',
  //    increaseArea: '20%' // optional
  //  });
  //});

body.hold-transition.login-page
.register-box
  .register-logo
    b> 校园蓝牙基站系统
    br
    h4 栖格科技
  /! /.login-logo
  .register-box-body
    p.login-box-msg 教师账户注册
    - if @response && !@response.is_successful?
      p.login-box-msg
        .alert.alert-warning.alert-dismissible
          button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
          i.icon.fa.fa-warning = @response.message
    = form_tag sign_up_users_path, name: 'sign_up_form', method: :post, novalidate: 'novalidate'
    .form-group.has-feedback
      input.form-control placeholder=("登录账号") type="text" name="username"/
    .form-group.has-feedback
      input.form-control placeholder=("密码") type="password" name="password"/
    .form-group.has-feedback
      input.form-control placeholder=("确认密码") type="password" name="conf_password"/
    .form-group.has-feedback
      input.form-control placeholder=("真实姓名") type="text" name="real_name"/
    .form-group.has-feedback
      input.form-control placeholder=("手环设备号") type="text" name="device_id"/
    .form-group.has-feedback
      input.form-control placeholder=("学科:(英语)") type="text" name="subject"/
    .row
      .col-xs-4.col-xs-offset-4
        button.btn.btn-primary.btn-block.btn-flat type="submit"  注册