config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :sign_in
      post :sign_in
      get :me
      get :sign_up
      post :sign_up

      get :me_detail
    end
  end

  # 楼层
  resources :floors, only: [:index, :create, :edit, :new, :show]

  # 班级
  resources :clazzs, only: [:index, :new, :create, :show]

  namespace :api do
    # 统计API
    resources :statistics, only: [:index] do
      collection do
        post :floor
      end
    end

    # 房间
    resources :rooms, only: [:update] do
      member do
        post :create_station
      end
    end

    # 楼层API
    resources :floors, only: [:index, :show] do
      member do
        post :create_room

        # 获取楼层房间
        get :rooms
      end

      collection do
        # 所有楼层->所有房间->房间内的基站 隐射表
        get :station_mapping
      end
    end

    # 基站数据更新
    resources :stations, only: [:update]

    # 班级
    resources :clazzs, only: [:index, :update, :create]

    # 语音消息
    resources :audio_messages do
      member do
        # 设置已读
        post :set_read
      end
    end

    # 老师
    resources :teachers do
      collection do
        # 获取评论
        get :comments

        get :audio_messages

        # 获取魔法棒配置
        get :sticker_configs

        # 更新魔法棒配置
        post :update_sticker_config

        # 添加魔法棒配置
        post :create_sticker_config
      end
    end

    # 轨迹
    resources :tracks, only: [:create]
  end

  namespace :board do
    # 养老院
    resources :nursing_home, only: [:index] do
      collection do
        # 获取页面数据
        get :page_data

        # 获取在线人员即时位置信息
        get :realtime_geo_data

        # 获取一天的历史轨迹
        get :footprints
      end
    end

    # 班级
    resources :clazzs, only: [:index, :show] do
      member do
        get :students_list
        get :comments
      end

      collection do
        # 创建评论
        post :create_comment

        # 创建语音信息
        post :create_audio_message

        # 获取教师列表接口
        get :teachers
      end
    end


  end

end

app/models/floor.rb
# == Schema Information
#
# Table name: floors
#
#  id         :integer          not null, primary key
#  name       :string(255)                            # 楼层名称
#  image      :text(65535)                            # 楼层cad图
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Floor < ActiveRecord::Base

  # 挂载图片
  mount_uploader :image, CadUploader

  # 通用查询方法
  include Concerns::Query::Methods

  # 关联房间/走道
  has_many :rooms

  #
  # 楼道列表查询接口
  #
  # @param options [Hash]
  #
  # @return [Response, Array] 状态，楼道列表
  #
  def self.query_all_with_options_for_api(options = {})
    floors = []
    response = Response.__rescue__ do |res|
      floors = Floor.includes(:rooms)
    end

    return response, floors
  end

  #
  # 单个楼道查询接口
  #
  # @param options [Hash]
  #
  # @return [Response, Array] 状态，楼道对象
  #
  def self.query_show_for_api(options={})
    floor = nil
    response = Response.__rescue__ do |res|
      id = options[:id]
      floor = Floor.query_first_by_id id

      res.__raise__(Response::Code::ERROR, '楼层不存在') if floor.blank?

    end

    return response, floor
  end

  #
  # 获取楼层的所有房间
  #
  # @param options [Hash]
  #
  # @return [Response, Array] 状态，房间数组
  #
  def self.query_rooms_in_floor_for_api(options={})
    rooms = []
    response = Response.__rescue__ do |res|
      id = options[:id]
      floor = Floor.query_first_by_id id

      res.__raise__(Response::Code::ERROR, '楼层不存在') if floor.blank?

      rooms = floor.rooms
    end

    return response, rooms
  end

  #
  # 为楼层添加走道/房间
  #
  # @param options [Hash]
  # option options [name] :名称
  # option options [location] :房间位置json
  #
  # @return [Response, Array] 状态，楼道对象
  #
  def self.create_room_with_options(options={})
    response = Response.__rescue__ do |res|
      id, name, location = options[:id], options[:name], options[:location]
      floor = Floor.query_first_by_id id

      res.__raise__(Response::Code::ERROR, '楼层不存在') if floor.blank?
      res.__raise__(Response::Code::ERROR, '参数错误') if name.blank? || location.blank?

      room = Room.new
      room.name = name
      room.location = location
      room.floor = floor
      room.save!
    end

    return response
  end

  #
  # 添加楼层api
  #
  # @param options [Hash]
  # option options [floor_name] :名称
  # option options [floor_cad] :楼层cad图
  #
  # @return [Response, Array] 状态
  #
  def self.create_with_options_for_api(options={})
    floor = nil
    response = Response.__rescue__ do |res|
      floor_name, floor_cad = options[:floor_name], options[:floor_cad]

      res.__raise__(Response::Code::ERROR, '参数错误') if floor_name.blank? || floor_cad.blank?

      puts "----------floor_cad-----:#{floor_cad}"

      floor = Floor.new
      floor.name = floor_name
      floor.image = floor_cad
      floor.save!
    end
    return response, floor
  end
end

app/controllers/api/floors_controller.rb
class Api::FloorsController < Api::ApiBaseController
  skip_before_filter :user_authenticate, only:[:station_mapping]
  def index
    @response, @floors = Floor.query_all_with_options_for_api(params)
  end

  def show
    @response, @floor = Floor.query_show_for_api(params)
  end

  def create_room
    @response = Floor.create_room_with_options(params)
  end

  def rooms
    @response, @rooms = Floor.query_rooms_in_floor_for_api(params)
  end

  # 获取每个楼层下的蓝牙基站信息 floors:[{name: '楼层一', rooms: [{name:'102', stations: [{...}]}]}]
  def station_mapping
    @response, @floors = Floor.query_all_with_options_for_api(params)
    @floors = @floors.includes({rooms: :stations})
  end

end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController

  def index
  end

  def show
    @floor_id = params[:id]
  end

  def new
  end

  def create
    @response, @floor = Floor.create_with_options_for_api(params)
  end
end

app/views/floors/create.slim
body.hold-transition.skin-black.sidebar-mini ng-controller='FloorNewController'
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    .content-wrapper
      /! Main content
      section.content
        .row
          .col-md-8.col-md-offset-2
            - if @response.is_successful?
              .callout.callout-success
                h4 楼层添加成功
                p
                  a href=(floor_path(@floor)) 现在去看看
            - else
              .callout.callout-danger
                h4 操作失败
                p = @response.message


  /.overlay ng-show="isLoadingForOnLineCountOfFloor"
    /  i.fa.fa-refresh.fa-spin

    /! /.box-body

    == include_slim 'app/views/common/footer'
    == include_slim 'app/views/common/control'

app/views/floors/index.slim
body.hold-transition.skin-black.sidebar-mini ng-controller='FloorIndexController'
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    /! /.sidebar-menu
    /! /.sidebar
    /! Content Wrapper. Contains page content
    .content-wrapper
      /! Content Header (Page header)
      section.content-header
      /! Main content
      section.content
        .row
          .col-md-12
            .box.box-info
              .box-header.with-border
                h3.box-title 楼层信息

              /! /.box-header
              .box-body style=("display: block;")
                .table-responsive
                  table.table.no-margin
                    thead
                      tr
                        th 名称
                        th 房间/走道数
                        th 操作
                    tbody
                      tr ng-repeat="floor in floors"
                        td
                          a ng-href=("{{'/floors/' + floor.id}}") ng-bind="floor.name"
                        td
                          span.label.label-success ng-bind="floor.room_count"
                        td
                          a.btn.btn-default.btn-xs role="button" ng-href=("{{'/floors/' + floor.id}}") 详情

              .box-footer.clearfix style=("display: block;")
                a.btn.btn-sm.btn-info.btn-flat.pull-left href=(new_floor_path)  新建
              .overlay ng-show="isLoadingForGetFloors"
                i.fa.fa-refresh.fa-spin
    == include_slim 'app/views/common/footer'
    == include_slim 'app/views/common/control'

app/views/floors/new.slim
body.hold-transition.skin-black.sidebar-mini ng-controller='FloorNewController'
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    .content-wrapper
      /! Main content
      section.content
        .row
          .col-md-8.col-md-offset-2
            .box.box-info
              .box-header.with-border
                h3.box-title 添加楼层
              .box-body
                = form_tag floors_path, name: 'post_floor_form', method: :post, multipart: true, remote: true
                  .form-group
                    label 楼层名称
                    .input-group
                      .input-group-addon
                        i.fa.fa-database
                      input.form-control type="text" name="floor_name"
                    .form-group
                      label for="floor-cad" 楼层CAD图
                      input#floor-cad type="file" name="floor_cad" /
                    /! /.table-responsive
                    /! /.box-body
                    .box-footer.clearfix style=("display: block;")
                      button.btn.btn-sm.btn-info.pull-right type='submit' 提交
              /.overlay ng-show="isLoadingForOnLineCountOfFloor"
              /  i.fa.fa-refresh.fa-spin

    /! /.box-body

    == include_slim 'app/views/common/footer'
      == include_slim 'app/views/common/control'

app/views/floors/show.slim
javascript:
  $(function () {
    $('#room-rightbar').css('max-height', $(window).height());
  });


body.hold-transition.skin-black.sidebar-mini ng-controller='FloorShowController' data-floorid=(@floor_id)
  #update-room-name.modal.fade role="dialog" tabindex="-1"
    .modal-dialog role="document"
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
          h4.modal-title 更新房间名
        .modal-body
          input.form-control ng-model='SelectedRoom.name' placeholder=("更新房间名") type="text" /
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  取消
          button.btn.btn-primary type="button" ng-click='ApplyUpdateRoom()'  保存
  .wrapper
    /! Main Header
    == include_slim 'app/views/common/nav'
    == include_slim 'app/views/common/sidebar'

    /! /.sidebar-menu
    /! /.sidebar
    /! Content Wrapper. Contains page content
    .content-wrapper
      /! Content Header (Page header)
      section.content-header
      /! Main content
      section.content
        .row
          .col-md-8
            .box
              .box-header.with-border
                h3.box-title 楼层CAD
                .box-tools.pull-right
                  button.btn.btn-sm.btn-box-tool.btn-flat 上传

              /! /.box-header
              .box-body
                #canvas-wrapper style="width: 100%;position: relative;"
                  img#canvas-image ng-src='{{floor.image}}' style=("width: 100%;") imageonload='ResizeCanvas()'
                  canvas#canvas style="position: absolute;width: 100%;height: 100%;left: 0; top: 0; display: block;"

              /! /.table-responsive
              /! /.box-body
              .box-footer.clearfix style=("display: block;")

              .overlay ng-show="isLoadingForGetFloorShow"
                i.fa.fa-refresh.fa-spin
          .col-md-4 ng-show='tempPath != null'
            .box.box-danger
              .box-header
                h3.box-title 添加房间
              .box-body
                /! Date dd/mm/yyyy
                .form-group
                  label 房间名称
                  .input-group
                    .input-group-addon
                      i.fa.fa-calendar
                    input.form-control data-mask="" type="text" ng-model='tempPathName'
                button.btn.btn-block.btn-success.btn-flat type="button" ng-click='CreateRoom()' ng-disabled='!CreateRoomBtnEnabled()' 提交
                button.btn.btn-block.btn-danger.btn-flat type="button" ng-click='tempPath = null;' 取消
          /! /.input group
          /! /.form group
          /! /.box-body
          .col-md-4

            .row ng-show='selectedStation != null'
              .col-md-12
                .box
                  .box-header.with-border
                    h3.box-title 编辑蓝牙基站
                  /! /.box-header
                  .box-body
                    .form-group
                      label 基站设备号
                      .input-group
                        .input-group-addon
                          i.fa.fa-database
                        input.form-control data-mask="" type="text" ng-model='selectedStation.device_id'
                    .form-group
                      label Group number
                      .input-group
                        .input-group-addon
                          i.fa.fa-sort-numeric-desc
                        input.form-control data-mask="" type="text" ng-model='selectedStation.group_number'
                    .form-group
                      label 坐标
                      .input-group
                        .input-group-addon
                          i.fa.fa-location-arrow
                        input.form-control data-mask="" type="text" ng-model='selectedStation.location' disabled='true'
                  /! /.table-responsive
                  /! /.box-body
                  .box-footer.clearfix style=("display: block;")
                    a.btn.btn-sm.btn-info.pull-right ng-click='UpdateStationForRoom()'  保存
                    a.btn-danger.btn.btn-sm.btn-info.pull-left ng-click='CancelSelectStation()'  取消
                  .overlay ng-show="isUpdatingStationForRoom"
                    i.fa.fa-refresh.fa-spin
            .row ng-show='tempBlueToothStation != null'
              .col-md-12
                .box
                  .box-header.with-border
                    h3.box-title 新建蓝牙基站
                  /! /.box-header
                  .box-body
                    .form-group
                      label 基站设备号
                      .input-group
                        .input-group-addon
                          i.fa.fa-database
                        input.form-control data-mask="" type="text" ng-model='tempBlueToothStation.device_id'
                    .form-group
                      label Group number
                      .input-group
                        .input-group-addon
                          i.fa.fa-sort-numeric-desc
                        input.form-control data-mask="" type="text" ng-model='tempBlueToothStation.group_number'
                    .form-group
                      label 坐标
                      .input-group
                        .input-group-addon
                          i.fa.fa-location-arrow
                        input.form-control data-mask="" type="text" ng-model='tempBlueToothStation.point' disabled='true'
                    .form-group
                      label 所属房间
                      .input-group
                        .input-group-addon
                          i.fa.fa-inbox
                        input.form-control data-mask="" type="text" ng-model='tempBlueToothStation.room.name' disabled='true'
                  /! /.table-responsive
                  /! /.box-body
                  .box-footer.clearfix style=("display: block;")
                    a.btn.btn-sm.btn-info.pull-right ng-click='CreateStationForRoom()'  添加基站
                    a.btn-danger.btn.btn-sm.btn-info.pull-left ng-click='tempBlueToothStation = null;'  取消
                  .overlay ng-show="isLoadingForGetFloorShow"
                    i.fa.fa-refresh.fa-spin
            .row
              .col-md-12 ng-show='tempPath == null'
                #room-rightbar.nav-tabs-custom style="overflow-y: scroll;"
                  ul.nav.nav-tabs
                    li.active
                      a aria-expanded="false" data-toggle="tab" href="#timeline"  房间/走道

                  .tab-content
                    #timeline.tab-pane.active
                      .small-box.bg-aqua ng-repeat='room in floor.rooms' ng-click='selectRoom($index)'
                        .inner
                          h3 房间:{{room.name}}
                          br
                          br
                        .icon
                          i.fa.fa-home
                        a.small-box-footer style='cursor: pointer;' ng-click='UpdateRoom(room)'
                          | 修改
                          i.fa.fa-arrow-circle-right

    /! /.tab-pane
    /! /.tab-content
    /! /.nav-tabs-custom
    == include_slim 'app/views/common/footer'
    == include_slim 'app/views/common/control'